name: CI/CD for Docker Image Deployment

on:
  # Detecta cambios en archivos htmllL en pull requests a la rama "test"
  pull_request:
    branches:
      - test

jobs:
  # Trabajo 1: Actualizar la imagen   Docker
  update_docker_image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Check out repository
        uses: actions/checkout@v4

      # Paso 2: Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 3: Construir y subir la imagen actualizada
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .               # Usa el Dockerfile desde la raíz
          push: true               # Sube la imagen a Docker Hub
          tags: dayanara1898/html-project:latest # Etiqueta como "latest"

  # Trabajo 2: Desplegar la nueva imagen en la instancia EC2
  deploy:
    name: Deploy Docker Container to EC2
    runs-on: ubuntu-latest
    needs: update_docker_image # Depende de que el trabajo anterior termine con éxito

    steps:
      # Paso 1: Configurar la clave SSH
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Paso 2: Conectarse a la instancia EC2 y actualizar el contenedor
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_INSTANCE_1 }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Detener y eliminar el contenedor si ya existe
            docker stop html-container || true
            docker rm html-container || true
            # Extraer la última versión de la imagen desde Docker Hub
            docker pull dayanara1898/html-project:latest
            # Iniciar un nuevo contenedor con la imagen actualizada
            docker run -d --name html-container -p 80:80 dayanara1898/html-project:latest
